# Local server
server:
  # port is used by spring-boot-admin
  port: 8080
  contextPath: /acecook

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/demo?user=root
  jpa:
    hibernate:
      show-sql: false